<?php
$candidatos = array(
    "0" => array(
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 01",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 011",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JOSE LUIS                     ",
            "apellido" => " JARAMILLO CASTRILLON              ",
            "cedula" => " 8294151",
            "sexo" => " M01",
        ),
    "1" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 01",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " ANDRES FELIPE                   ",
            "apellido" => " GUERRA HOYOS                                    ",
            "cedula" => " 71394456",
            "sexo" => " M02",
        ),
    "2" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 01",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " OLMEDO DE JESUS                                   ",
            "apellido" => " LOPEZ MARTINEZ                                    ",
            "cedula" => " 98538265",
            "sexo" => " M03",
        ),
    "3" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 01",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 679",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " LUIS                                              ",
            "apellido" => " PEREZ                                             ",
            "cedula" => " 70031781",
            "sexo" => " M04",
        ),
    "4" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 01",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 344",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " FEDERICO                                          ",
            "apellido" => " RESTREPO                                          ",
            "cedula" => " 70546837",
            "sexo" => " M05",
        ),
    "5" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 03",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 104",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JUAN JOSE                                         ",
            "apellido" => "ACU�A COLPAS                                      ",
            "cedula" => " 3758662",
            "sexo" => " M01",
        ),
    "6" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 03",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 048",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JUAN ALBERTO                                      ",
            "apellido" => " GARCIA ESTRADA                                    ",
            "cedula" => " 9173482",
            "sexo" => " M02",
        ),
    "7" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 03",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " MANUEL ANTONIO                                    ",
            "apellido" => " DIAZ JIMENO                                       ",
            "cedula" => " 72150598",
            "sexo" => " M03",
        ),
    "8" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 03",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 208",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => "ALFREDO ESTEBAN                                   ",
            "apellido" => " VARELA DE LA ROSA                                 ",
            "cedula" => " 8511671",
            "sexo" => " M04",
        ),
    "9" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 03",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " EDUARDO IGNACIO                                   ",
            "apellido" => " VERANO DE LA ROSA                                 ",
            "cedula" => " 7458361",
            "sexo" => " M05",
        ),
    "10" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 05",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 776",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " ROSARIO CECILIA                                   ",
            "apellido" => " RICARDO BRAY                                      ",
            "cedula" => " 33173299",
            "sexo" => " F01",
        ),
    "11" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 05",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " YOLANDA                                           ",
            "apellido" => " WONG BALDIRIS                                     ",
            "cedula" => " 45760403",
            "sexo" => " F02",
        ),
    "12" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 05",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " DUMEK JOSE                                        ",
            "apellido" => " TURBAY PAZ                                        ",
            "cedula" => " 73547859",
            "sexo" => " M03",
        ),
    "13" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 05",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 014",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " COMITE PROMOTOR                                   ",
            "apellido" => " VOTO EN BLANCO                                    ",
            "cedula" => " 99999993",
            "sexo" => " M04",
        ),
    "14" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 07",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 094",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JUAN DE JESUS                                     ",
            "apellido" => " CORDOBA SUAREZ                                    ",
            "cedula" => " 4058857",
            "sexo" => " M01",
        ),
    "15" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 07",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " CESAR AUGUSTO                                     ",
            "apellido" => " PACHON ACHURY                                     ",
            "cedula" => " 7183470",
            "sexo" => " M02",
        ),
    "16" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 07",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 061",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " CARLOS ANDRES                                     ",
            "apellido" => "AMAYA RODRIGUEZ                                   ",
            "cedula" => " 4209025",
            "sexo" => " M03",
        ),
    "17" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 07",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 117",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " OSMAN HIPOLITO                                    ",
            "apellido" => " ROA SARMIENTO                                     ",
            "cedula" => " 19384581",
            "sexo" => " M04",
        ),
    "18" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 07",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " GONZALO                                           ",
            "apellido" => " GUARIN VIVAS                                      ",
            "cedula" => " 7217655",
            "sexo" => " M05",
        ),
    "19" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 09",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 210",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JORGE HERNAN                                      ",
            "apellido" => " MESA BOTERO                                       ",
            "cedula" => " 19366014",
            "sexo" => " M01",
        ),
    "20" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 09",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JORGE EDUARDO                                     ",
            "apellido" => " ARBELAEZ HOYOS                                    ",
            "cedula" => " 79152647",
            "sexo" => " M02",
        ),
    "21" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 09",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 122",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " GUIDO                                             ",
            "apellido" => " ECHEVERRI PIEDRAHITA                              ",
            "cedula" => " 1418637",
            "sexo" => " M03",
        ),
    "22" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 09",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 259",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " CARLOS URIEL                                      ",
            "apellido" => " NARANJO VELEZ                                     ",
            "cedula" => " 10239570",
            "sexo" => " M04",
        ),
    "23" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 11",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 184",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " CARLOS FELIPE                                     ",
            "apellido" => " MU�OZ BOLA�OS                                     ",
            "cedula" => " 10547913",
            "sexo" => " M01",
        ),
    "24" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 11",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 270",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " OSCAR RODRIGO                                     ",
            "apellido" => " CAMPO HURTADO                                     ",
            "cedula" => " 76318220",
            "sexo" => " M02",
        ),
    "25" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 11",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " LEONARDO ALFONSO                                  ",
            "apellido" => " BARRERO GORDILLO                                  ",
            "cedula" => " 19410615",
            "sexo" => " M03",
        ),
    "26" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 11",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 612",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " GILBERTO                                          ",
            "apellido" => " MU�OZ CORONADO                                    ",
            "cedula" => " 14882225",
            "sexo" => " M04",
        ),
    "27" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 12",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 207",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => "ARTURO RAFAEL                                     ",
            "apellido" => " CALDERON RIVADENEIRA                              ",
            "cedula" => " 77036038",
            "sexo" => " M01",
        ),
    "28" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 12",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " FRANCISCO FERNANDO                                ",
            "apellido" => " OVALLE ANGARITA                                   ",
            "cedula" => " 79340571",
            "sexo" => " M02",
        ),
    "29" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 12",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 565",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " IMELDA                                            ",
            "apellido" => " DAZA COTES                                        ",
            "cedula" => " 41419142",
            "sexo" => " F03",
        ),
    "30" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 13",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 840",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " EDWIN JOSE                                        ",
            "apellido" => " BESAILE FAYAD                                     ",
            "cedula" => " 78739340",
            "sexo" => " M01",
        ),
    "31" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 13",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " NICOLAS REINEL                                    ",
            "apellido" => " PICON BARRERA                                     ",
            "cedula" => " 79380040",
            "sexo" => " M02",
        ),
    "32" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 13",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " CARLOS DAVID                                      ",
            "apellido" => " GOMEZ ESPITIA                                     ",
            "cedula" => " 80091894",
            "sexo" => " M03",
        ),
    "33" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 15",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " RAFAEL ANTONIO                                    ",
            "apellido" => " BALLEN MOLINA                                     ",
            "cedula" => " 3266361",
            "sexo" => " M01",
        ),
    "34" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 15",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 109",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JORGE EMILIO                                      ",
            "apellido" => " REY ANGEL                                         ",
            "cedula" => " 79632322",
            "sexo" => " M02",
        ),
    "35" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 15",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 268",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " NANCY PATRICIA                                    ",
            "apellido" => " GUTIERREZ CASTA�EDA                               ",
            "cedula" => " 51710983",
            "sexo" => " F03",
        ),
    "36" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 17",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 788",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JHOANY CARLOS ALBERTO                             ",
            "apellido" => " PALACIOS MOSQUERA                                 ",
            "cedula" => " 82383138",
            "sexo" => " M01",
        ),
    "37" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 17",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 007",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " NIGERIA                                           ",
            "apellido" => " RENTERIA LOZANO                                   ",
            "cedula" => " 43533953",
            "sexo" => " F02",
        ),
    "38" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 17",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " JESUS ORACIO                                      ",
            "apellido" => " MORENO MOSQUERA                                   ",
            "cedula" => " 11935624",
            "sexo" => " M03",
        ),
    "39" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 17",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 003",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " FRANCISCO ABDIA                                   ",
            "apellido" => " VELASQUEZ SALGUERO                                ",
            "cedula" => " 79421651",
            "sexo" => " M04",
        ),
    "40" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 17",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 791",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => "AMAN ALIRIO                                       ",
            "apellido" => "ASPRILLA MOSQUERA                                 ",
            "cedula" => " 82382683",
            "sexo" => " M05",
        ),
    "41" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 17",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " MELECIO                                           ",
            "apellido" => " QUINTO ARIAS                                      ",
            "cedula" => " 11795265",
            "sexo" => " M06",
        ),
    "42" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 19",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 011",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " GUSTAVO                                           ",
            "apellido" => " BRI�EZ VILLA                                      ",
            "cedula" => " 17192032",
            "sexo" => " M01",
        ),
    "43" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 19",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " RIGOBERTO                                         ",
            "apellido" => " CICERI ARRIGUI                                    ",
            "cedula" => " 19054012",
            "sexo" => " M02",
        ),
    "44" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 19",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 088",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " CARLOS JULIO                                      ",
            "apellido" => " GONZALEZ VILLA                                    ",
            "cedula" => " 79277306",
            "sexo" => " M03",
        ),
    "45" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 19",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " ESPERANZA                                         ",
            "apellido" => "ANDRADE DE OSSO                                   ",
            "cedula" => " 41706818",
            "sexo" => " F04",
        ),
    "46" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 19",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " WILFRAND                                          ",
            "apellido" => " CUENCA ZULETA                                     ",
            "cedula" => " 7702448",
            "sexo" => " M05",
        ),
    "47" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 19",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 236",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " CARLOS RAMIRO                                     ",
            "apellido" => " CHAVARRO CUELLAR                                  ",
            "cedula" => " 12194906",
            "sexo" => " M06",
        ),
    "48" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 21",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " ROSA                                              ",
            "apellido" => " COTES DE ZU�IGA                                   ",
            "cedula" => " 36539388",
            "sexo" => " F01",
        ),
    "49" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 21",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JORGE LUIS                                        ",
            "apellido" => " LOPEZ AGUILAR                                     ",
            "cedula" => " 85461805",
            "sexo" => " M02",
        ),
    "50" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 21",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " JOAQUIN JOSE                                      ",
            "apellido" => " VIVES PEREZ                                       ",
            "cedula" => " 12556245",
            "sexo" => " M03",
        ),
    "51" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 23",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => "AFRANIO GUMERCINDO                                ",
            "apellido" => " RODRIGUEZ ROSERO                                  ",
            "cedula" => " 12981561",
            "sexo" => " M01",
        ),
    "52" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 23",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 506",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " CAMILO                                            ",
            "apellido" => " ROMERO                                            ",
            "cedula" => " 98394084",
            "sexo" => " M02",
        ),
    "53" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 23",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " EDUARDO JOSE                                      ",
            "apellido" => "ALVARADO SANTANDER                                ",
            "cedula" => " 12968252",
            "sexo" => " M03",
        ),
    "54" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 23",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " JHON ALEXANDER                                    ",
            "apellido" => " ROJAS CABRERA                                     ",
            "cedula" => " 98383107",
            "sexo" => " M04",
        ),
    "55" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 23",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 007",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " NELSON JESUS                                      ",
            "apellido" => " LEITON PORTILLA                                   ",
            "cedula" => " 12991545",
            "sexo" => " M05",
        ),
    "56" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 24",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 063",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " VICTOR MANUEL                                     ",
            "apellido" => " TAMAYO VARGAS                                     ",
            "cedula" => " 4582036",
            "sexo" => " M01",
        ),
    "57" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 24",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 209",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " LUZ YASMID                                        ",
            "apellido" => " LOPEZ VELEZ                                       ",
            "cedula" => " 42104345",
            "sexo" => " F02",
        ),
    "58" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 24",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 002",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " SIGIFREDO                                         ",
            "apellido" => " SALAZAR OSORIO                                    ",
            "cedula" => " 18502691",
            "sexo" => " M03",
        ),
    "59" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 25",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " GIOVANNI                                          ",
            "apellido" => " VILLAMIZAR LAGUADO                                ",
            "cedula" => " 88227939",
            "sexo" => " M01",
        ),
    "60" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 25",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 223",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JUDITH                                            ",
            "apellido" => " MALDONADO MOJICA                                  ",
            "cedula" => " 37511163",
            "sexo" => " F02",
        ),
    "61" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 25",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " RAMON ELI                                         ",
            "apellido" => " TAMARA RIVERA                                     ",
            "cedula" => " 13256146",
            "sexo" => " M03",
        ),
    "62" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 25",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " MILLA PATRICIA                                    ",
            "apellido" => " ROMERO SOTO                                       ",
            "cedula" => " 60400908",
            "sexo" => " F04",
        ),
    "63" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 25",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 002",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " JUAN CARLOS                                       ",
            "apellido" => " GARCIA HERREROS CABRERA                           ",
            "cedula" => " 13438410",
            "sexo" => " M05",
        ),
    "64" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 25",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 316",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " WILLIAM                                           ",
            "apellido" => " VILLAMIZAR LAGUADO                                ",
            "cedula" => " 13485061",
            "sexo" => " M06",
        ),
    "65" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 26",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " NESTOR DANIEL                                     ",
            "apellido" => " GARCIA COLORADO                                   ",
            "cedula" => " 89008959",
            "sexo" => " M01",
        ),
    "66" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 26",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 007",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JAVIER ALEJANDRO                                  ",
            "apellido" => " VASQUEZ JARAMILLO                                 ",
            "cedula" => " 89000440",
            "sexo" => " M02",
        ),
    "67" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 26",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 410",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " CARLOS EDUARDO                                    ",
            "apellido" => " OSORIO BURITICA                                   ",
            "cedula" => " 8405537",
            "sexo" => " M03",
        ),
    "68" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 26",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 056",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " SANDRA MILENA                                     ",
            "apellido" => " GOMEZ FAJARDO                                     ",
            "cedula" => " 41929672",
            "sexo" => " F04",
        ),
    "69" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 27",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " IVAN FERNANDO                                     ",
            "apellido" => "AGUILAR ZAMBRANO                                  ",
            "cedula" => " 91514530",
            "sexo" => " M01",
        ),
    "70" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 27",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " DIDIER ALBERTO                                    ",
            "apellido" => " TAVERA AMADO                                      ",
            "cedula" => " 91490930",
            "sexo" => " M02",
        ),
    "71" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 27",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " HOLGER HORACIO                                    ",
            "apellido" => " DIAZ HERNANDEZ                                    ",
            "cedula" => " 8732300",
            "sexo" => " M03",
        ),
    "72" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 27",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 015",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " CARLOS FERNANDO DE JESUS                          ",
            "apellido" => " SANCHEZ AGUIRRE                                   ",
            "cedula" => " 91212339",
            "sexo" => " M04",
        ),
    "73" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 27",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 028",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " PEDRO LEONIDAS                                    ",
            "apellido" => " GOMEZ GOMEZ                                       ",
            "cedula" => " 13804037",
            "sexo" => " M05",
        ),
    "74" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 28",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 003",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " MILENE                                            ",
            "apellido" => " JARAVA DIAZ                                       ",
            "cedula" => " 64575021",
            "sexo" => " F01",
        ),
    "75" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 28",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JUAN MIGUEL                                       ",
            "apellido" => " NAVARRO NAVARRO                                   ",
            "cedula" => " 92031271",
            "sexo" => " M02",
        ),
    "76" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 28",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " EDGAR ENRIQUE                                     ",
            "apellido" => " MARTINEZ ROMERO                                   ",
            "cedula" => " 6808462",
            "sexo" => " M03",
        ),
    "77" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 28",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " NADIM ISAAC                                       ",
            "apellido" => " MISERQUE CARDENAS                                 ",
            "cedula" => " 92505114",
            "sexo" => " M04",
        ),
    "78" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 29",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JAIME EDUARDO                                     ",
            "apellido" => " REYES MARTINEZ                                    ",
            "cedula" => " 93378891",
            "sexo" => " M01",
        ),
    "79" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 29",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 447",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " MAURICIO                                          ",
            "apellido" => " JARAMILLO MARTINEZ                                ",
            "cedula" => " 19300805",
            "sexo" => " M02",
        ),
    "80" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 29",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 823",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " OSCAR                                             ",
            "apellido" => " BARRETO QUIROGA                                   ",
            "cedula" => " 14240339",
            "sexo" => " M03",
        ),
    "81" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 29",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 504",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " CARLOS ARMANDO                                    ",
            "apellido" => " GARCIA ORJUELA                                    ",
            "cedula" => " 19079760",
            "sexo" => " M04",
        ),
    "82" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 31",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " FERNANDO                                          ",
            "apellido" => " TOLOZA COLORADO                                   ",
            "cedula" => " 87190684",
            "sexo" => " M01",
        ),
    "83" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 31",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 373",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JORGE ALEJANDRO                                   ",
            "apellido" => " OCAMPO GIRALDO                                    ",
            "cedula" => " 14838849",
            "sexo" => " M02",
        ),
    "84" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 31",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " DILIAN FRANCISCA                                  ",
            "apellido" => " TORO TORRES                                       ",
            "cedula" => " 29538603",
            "sexo" => " F03",
        ),
    "85" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 31",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " OSCAR                                             ",
            "apellido" => " GAMBOA ZU�IGA                                     ",
            "cedula" => " 16479364",
            "sexo" => " M04",
        ),
    "86" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 31",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " MAURICIO ERNESTO                                  ",
            "apellido" => " OSPINA GOMEZ                                      ",
            "cedula" => " 94456251",
            "sexo" => " M05",
        ),
    "87" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 31",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 385",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " CHRISTIAN MUNIR                                   ",
            "apellido" => " GARCES ALJURE                                     ",
            "cedula" => " 94503511",
            "sexo" => " M06",
        ),
    "88" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 40",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " CARMEN SIRENIA                                    ",
            "apellido" => " SARAY TOVAR                                       ",
            "cedula" => " 51603421",
            "sexo" => " F01",
        ),
    "89" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 40",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 003",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " EDGAR FERNANDO                                    ",
            "apellido" => " GUZMAN ROBLES                                     ",
            "cedula" => " 86057493",
            "sexo" => " M02",
        ),
    "90" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 40",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " HERNANDO                                          ",
            "apellido" => " POSSO PARALES                                     ",
            "cedula" => " 17584601",
            "sexo" => " M03",
        ),
    "91" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 40",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 355",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " RICARDO                                           ",
            "apellido" => "ALVARADO BESTENE                                  ",
            "cedula" => " 17580967",
            "sexo" => " M04",
        ),
    "92" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 44",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " LUIS ANTONIO                                      ",
            "apellido" => " SERRANO MORALES                                   ",
            "cedula" => " 19357374",
            "sexo" => " M01",
        ),
    "93" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 44",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 002",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => "ARNULFO                                           ",
            "apellido" => " GASCA TRUJILLO                                    ",
            "cedula" => " 17626998",
            "sexo" => " M02",
        ),
    "94" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 44",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => "ALVARO                                            ",
            "apellido" => " PACHECO ALVAREZ                                   ",
            "cedula" => " 17639177",
            "sexo" => " M03",
        ),
    "95" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 44",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " LUIS ANTONIO                                      ",
            "apellido" => " RUIZ CICERY                                       ",
            "cedula" => " 17683329",
            "sexo" => " M04",
        ),
    "96" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 46",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " JOEL                                              ",
            "apellido" => " OLMOS CORDERO                                     ",
            "cedula" => " 9431616",
            "sexo" => " M01",
        ),
    "97" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 46",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JOSUE ALIRIO                                      ",
            "apellido" => " BARRERA RODRIGUEZ                                 ",
            "cedula" => " 74753205",
            "sexo" => " M02",
        ),
    "98" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 46",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 663",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " HECTOR JULIO                                      ",
            "apellido" => " RAMOS PRIETO                                      ",
            "cedula" => " 74795537",
            "sexo" => " M03",
        ),
    "99" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 46",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 556",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " LILIAN FERNANDA                                   ",
            "apellido" => " SALCEDO RESTREPO                                  ",
            "cedula" => " 47429463",
            "sexo" => " F04",
        ),
    "100" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 48",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " OVIDIO                                            ",
            "apellido" => " MEJIA MARULANDA                                   ",
            "cedula" => " 12542246",
            "sexo" => " M01",
        ),
    "101" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 48",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " ONEIDA RAYETH                                     ",
            "apellido" => " PINTO PEREZ                                       ",
            "cedula" => " 56053991",
            "sexo" => " F02",
        ),
    "102" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 50",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 003",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " GUSTAVO                                           ",
            "apellido" => " GONZALEZ                                          ",
            "cedula" => " 4133824",
            "sexo" => " M01",
        ),
    "103" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 50",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " BORIS RAFAEL                                      ",
            "apellido" => " MARTINEZ HERNANDEZ                                ",
            "cedula" => " 19003430",
            "sexo" => " M02",
        ),
    "104" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 50",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 278",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " JAVIER ELIECER                                    ",
            "apellido" => " ZAPATA PARRADO                                    ",
            "cedula" => " 86045269",
            "sexo" => " M03",
        ),
    "105" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 50",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 007",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => "ALIPIO                                            ",
            "apellido" => " HORACIO MEDINA                                    ",
            "cedula" => " 19016433",
            "sexo" => " M04",
        ),
    "106" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 50",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " LUIS ANTONIO                                      ",
            "apellido" => " RODRIGUEZ LOPEZ                                   ",
            "cedula" => " 19001975",
            "sexo" => " M05",
        ),
    "107" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 50",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 084",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => "ANATOLIO                                          ",
            "apellido" => " HERNANDEZ LOZANO                                  ",
            "cedula" => " 2980574",
            "sexo" => " M06",
        ),
    "108" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 52",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 604",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " CLAUDIA MARCELA                                   ",
            "apellido" => "AMAYA GARCIA                                      ",
            "cedula" => " 40385221",
            "sexo" => " F01",
        ),
    "109" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 52",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " CARLOS EDUARDO                                    ",
            "apellido" => " CANO HERNANDEZ                                    ",
            "cedula" => " 3286593",
            "sexo" => " M02",
        ),
    "110" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 52",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 012",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " HERNAN ALEXIS                                     ",
            "apellido" => " GOMEZ NI�O                                        ",
            "cedula" => " 86066024",
            "sexo" => " M03",
        ),
    "111" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 52",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " DARIO                                             ",
            "apellido" => " VASQUEZ SANCHEZ                                   ",
            "cedula" => " 17309444",
            "sexo" => " M04",
        ),
    "112" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 52",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 009",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " LUIS CARLOS EFRAIN                                ",
            "apellido" => " TORRES RUEDA                                      ",
            "cedula" => " 17314575",
            "sexo" => " M05",
        ),
    "113" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 54",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 616",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " YEYSON EFRAIN                                     ",
            "apellido" => " PINEDA ALFONSO                                    ",
            "cedula" => " 80011947",
            "sexo" => " M01",
        ),
    "114" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 54",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 358",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " SANTOS MARIA                                      ",
            "apellido" => " SUAREZ MELO                                       ",
            "cedula" => " 97611659",
            "sexo" => " M02",
        ),
    "115" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 54",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => "ANDRES FABIAN                                     ",
            "apellido" => "AMAYA                                             ",
            "cedula" => " 86048910",
            "sexo" => " M03",
        ),
    "116" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 54",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " NEBIO DE JESUS                                    ",
            "apellido" => " ECHEVERRY CADAVID                                 ",
            "cedula" => " 10056431",
            "sexo" => " M04",
        ),
    "117" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 54",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " FLOR PIEDAD                                       ",
            "apellido" => " CORTES CRISTANCHO                                 ",
            "cedula" => " 51965517",
            "sexo" => " F05",
        ),
    "118" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 54",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 188",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " CONSTANTINO                                       ",
            "apellido" => " RODRIGUEZ CALVO                                   ",
            "cedula" => " 18223048",
            "sexo" => " M06",
        ),
    "119" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 56",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 003",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " EVERTH JULIO                                      ",
            "apellido" => " HAWKINS SJOGREEN                                  ",
            "cedula" => " 18004454",
            "sexo" => " M01",
        ),
    "120" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 56",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JORGE                                             ",
            "apellido" => " MENDEZ HERNANDEZ                                  ",
            "cedula" => " 18008270",
            "sexo" => " M02",
        ),
    "121" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 56",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 493",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " RONALD                                            ",
            "apellido" => " HOUSNI JALLER                                     ",
            "cedula" => " 15244179",
            "sexo" => " M03",
        ),
    "122" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 56",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 007",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " LIDONEL CREMLIN                                   ",
            "apellido" => " BENT LLERENA                                      ",
            "cedula" => " 18004097",
            "sexo" => " M04",
        ),
    "123" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 007",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " HAROLD AUGUSTO                                    ",
            "apellido" => " VALENCIA INFANTE                                  ",
            "cedula" => " 6565578",
            "sexo" => " M01",
        ),
    "124" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 002",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JHON ALEX                                         ",
            "apellido" => " BENJUMEA MORENO                                   ",
            "cedula" => " 15889318",
            "sexo" => " M02",
        ),
    "125" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " MANUEL ANTONIO                                    ",
            "apellido" => " CAREBILLA CUELLAR                                 ",
            "cedula" => " 6565585",
            "sexo" => " M03",
        ),
    "126" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 089",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " JHON CARLOS                                       ",
            "apellido" => " PALOMARES BABILONIA                               ",
            "cedula" => " 6567089",
            "sexo" => " M04",
        ),
    "127" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " CELSO                                             ",
            "apellido" => " PINEDA BERNAL                                     ",
            "cedula" => " 15888944",
            "sexo" => " M05",
        ),
    "128" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " LEVY                                              ",
            "apellido" => "ANDOKE ANDOKE                                     ",
            "cedula" => " 15875491",
            "sexo" => " M06",
        ),
    "129" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 007",
            "preferente" => " 1",
            "nombre" => " CASIMIRO                                          ",
            "apellido" => " CABRERA RODRIGUEZ                                 ",
            "cedula" => " 18202701",
            "sexo" => " M07",
        ),
    "130" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 60",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 003",
            "cod_candidato" => " 008",
            "preferente" => " 1",
            "nombre" => " HERNANDO EMILIO                                   ",
            "apellido" => " ZAMBRANO PANTOJA                                  ",
            "cedula" => " 17190009",
            "sexo" => " M08",
        ),
    "131" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 64",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 096",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " SORREL PARISA                                     ",
            "apellido" => "AROCA RODRIGUEZ                                   ",
            "cedula" => " 52420046",
            "sexo" => " F01",
        ),
    "132" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 64",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 002",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JORGE ELIECER                                     ",
            "apellido" => " CORAL RIVAS                                       ",
            "cedula" => " 16626326",
            "sexo" => " M02",
        ),
    "133" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 64",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 067",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " REINALDO                                          ",
            "apellido" => " VELASQUEZ RAMIREZ                                 ",
            "cedula" => " 18147853",
            "sexo" => " M03",
        ),
    "134" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 64",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 006",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " FAVIO ARTURO                                      ",
            "apellido" => " PAZ ORTIZ                                         ",
            "cedula" => " 97471330",
            "sexo" => " M04",
        ),
    "135" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 68",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 646",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " HENRY FERNANDO                                    ",
            "apellido" => " CORREAL HERRERA                                   ",
            "cedula" => " 17347255",
            "sexo" => " M01",
        ),
    "136" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 68",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 004",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => " JES�S MARIA                                       ",
            "apellido" => " V�SQUEZ CAICEDO                                   ",
            "cedula" => " 18202466",
            "sexo" => " M02",
        ),
    "137" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 72",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 001",
            "cod_candidato" => " 001",
            "preferente" => " 1",
            "nombre" => " HENRY                                             ",
            "apellido" => " SILVA MECHE                                       ",
            "cedula" => " 74815019",
            "sexo" => " M01",
        ),
    "138" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 72",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 013",
            "cod_candidato" => " 002",
            "preferente" => " 1",
            "nombre" => "ALFREDO                                           ",
            "apellido" => " GONZALEZ MARAGUA                                  ",
            "cedula" => " 19208907",
            "sexo" => " M02",
        ),
    "139" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 72",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 186",
            "cod_candidato" => " 003",
            "preferente" => " 1",
            "nombre" => " GUSTAVO                                           ",
            "apellido" => " LONDO�O GARCIA                                    ",
            "cedula" => " 16212775",
            "sexo" => " M03",
        ),
    "140" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 72",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 005",
            "cod_candidato" => " 004",
            "preferente" => " 1",
            "nombre" => " CLAUDIA MARIA                                     ",
            "apellido" => " CEPEDA URRUTIA                                    ",
            "cedula" => " 52263462",
            "sexo" => " F04",
        ),
    "141" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 72",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 064",
            "cod_candidato" => " 005",
            "preferente" => " 1",
            "nombre" => " LUIS CARLOS                                       ",
            "apellido" => "ALVAREZ MORALES                                   ",
            "cedula" => " 17347153",
            "sexo" => " M05",
        ),
    "142" => array(
        
            "corporacion" => " 001",
            "cod_circunscripcion" => " 1",
            "cod_departamento" => " 72",
            "cod_municipio" => " 000",
            "cod_comuna" => " 00",
            "cod_partido" => " 010",
            "cod_candidato" => " 006",
            "preferente" => " 1",
            "nombre" => " ROSALBA                                           ",
            "apellido" => " JIMENEZ AMAYA                                     ",
            "cedula" => " 21229599",
            "sexo" => " F06",
        ),
);